create table "public"."contact_family_children" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "firstName" text not null,
    "middleName" text not null,
    "lastName" text not null,
    "email" text not null,
    "relationType" text not null,
    "liveTogetherSince" text not null,
    "liveTogetherUntil" text not null,
    "DependentStatus" text not null,
    "householdMember" boolean not null,
    "headOfHousehold" boolean not null,
    "derivativeApplicant" boolean not null,
    "principalApplicant" boolean not null,
    "user" uuid default auth.uid()
);


alter table "public"."contact_family_children" enable row level security;

CREATE UNIQUE INDEX contact_family_children_pkey ON public.contact_family_children USING btree (id);

alter table "public"."contact_family_children" add constraint "contact_family_children_pkey" PRIMARY KEY using index "contact_family_children_pkey";

alter table "public"."contact_family_children" add constraint "contact_family_children_user_fkey" FOREIGN KEY ("user") REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."contact_family_children" validate constraint "contact_family_children_user_fkey";

grant delete on table "public"."contact_family_children" to "anon";

grant insert on table "public"."contact_family_children" to "anon";

grant references on table "public"."contact_family_children" to "anon";

grant select on table "public"."contact_family_children" to "anon";

grant trigger on table "public"."contact_family_children" to "anon";

grant truncate on table "public"."contact_family_children" to "anon";

grant update on table "public"."contact_family_children" to "anon";

grant delete on table "public"."contact_family_children" to "authenticated";

grant insert on table "public"."contact_family_children" to "authenticated";

grant references on table "public"."contact_family_children" to "authenticated";

grant select on table "public"."contact_family_children" to "authenticated";

grant trigger on table "public"."contact_family_children" to "authenticated";

grant truncate on table "public"."contact_family_children" to "authenticated";

grant update on table "public"."contact_family_children" to "authenticated";

grant delete on table "public"."contact_family_children" to "service_role";

grant insert on table "public"."contact_family_children" to "service_role";

grant references on table "public"."contact_family_children" to "service_role";

grant select on table "public"."contact_family_children" to "service_role";

grant trigger on table "public"."contact_family_children" to "service_role";

grant truncate on table "public"."contact_family_children" to "service_role";

grant update on table "public"."contact_family_children" to "service_role";

create policy "authenticated"
on "public"."contact_family_children"
as permissive
for all
to authenticated
using (true);



